included:
  - Sources
  - Tests
excluded:
  - .build/

line_length: 200

trailing_comma:
  mandatory_comma: true

identifier_name:
  allowed_symbols:
    - "_"
  excluded:
    - a
    - b
    - id
    - v
    - i
    - c
  min_length: 3
  max_length: 40

large_tuple:
  warning: 7
  error: 8